services:
  accounts:
    image: "jvmitenas/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    networks:
      - jvmitenas
    deploy:
      resources:
        limits:
          memory: 700m
  loans:
    image: "jvmitenas/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    networks:
      - jvmitenas
    deploy:
      resources:
        limits:
          memory: 700m
  cards:
    image: "jvmitenas/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    networks:
      - jvmitenas
    deploy:
      resources:
        limits:
          memory: 700m
networks:
  jvmitenas:
    driver: "bridge"